@startuml
actor Usuario 

participant Frontend
participant "Backend (Express)" as Backend 
database Supabase

Usuario -> Frontend : Seleccionar Perfil
Frontend -> Backend : Get /users/me
Backend -> Backend : Validar JWT

alt JWT válido
    Backend -> Backend : Consultar información del perfil
    Backend -> Supabase : Consultar registro

    Supabase --> Backend : Datos del perfil
    Backend --> Frontend : 200 OK + Datos del perfil
    Frontend --> Usuario : Mostrar datos del perfil
else JWT inválido 
    Backend --> Frontend : 401 unauthorized
    Frontend --> Usuario : Debe de iniciar sesión
end
@enduml


