name: CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: src/backend/package-lock.json

      - name: Instalar dependencias
        working-directory: src/backend
        run: npm ci

      - name: Ejecutar pruebas unitarias
        working-directory: src/backend
        run: npm test

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: src/frontend/package-lock.json

      - name: Instalar dependencias
        working-directory: src/frontend
        run: npm ci

      - name: Compilar frontend
        working-directory: src/frontend
        run: npm run build